use serde::{Deserialize, Serialize};

use crate::model::Allocation;

/// Represents a batch of allocations (decisions) generated by a strategy.
/// Vectorized for performance and efficiency.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AllocationBatch {
    allocations: Vec<Allocation>,
}

impl AllocationBatch {
    /// Creates a new AllocationBatch.
    pub fn new(allocations: Vec<Allocation>) -> Self {
        Self { allocations }
    }

    pub fn get_allocations(&self) -> &[Allocation] {
        &self.allocations
    }

    pub fn len(&self) -> usize {
        self.allocations.len()
    }

    pub fn is_empty(&self) -> bool {
        self.allocations.is_empty()
    }

    pub fn iter(&self) -> std::slice::Iter<'_, Allocation> {
        self.allocations.iter()
    }
}

impl From<Vec<Allocation>> for AllocationBatch {
    fn from(allocations: Vec<Allocation>) -> Self {
        Self::new(allocations)
    }
}

impl Into<Vec<Allocation>> for AllocationBatch {
    fn into(self) -> Vec<Allocation> {
        self.allocations
    }
}

impl IntoIterator for AllocationBatch {
    type Item = Allocation;
    type IntoIter = std::vec::IntoIter<Self::Item>;

    fn into_iter(self) -> Self::IntoIter {
        self.allocations.into_iter()
    }
}
